/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuralSandbox;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import neuralSandbox.Dialogs.NeuralNetworkSetting;
import neuralSandbox.Dialogs.PopulationSetting;
import neuralSandbox.genetics.Population;
import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Kurka
 */
public class MainFrame extends javax.swing.JFrame {
    private final Playground pg;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        pg = new Playground(this);
        initComponents();
        myInitComponents();
        
        setVisibleStatus(false);
        resumeLearningButton.setVisible(false);
    }

    private void myInitComponents() {
        playgroundPanel.add(pg);
    }
    
    public Playground getPlayground() {
        return pg;
    }
    
    public javax.swing.JPanel getPlaygroundPanel() {
        return playgroundPanel;
    }
    
    public void setGenerationValue(int gen) {
        generationCountLabel.setText("Generation: "+gen);
    }
    
    public void setFitnessValue(double fitness) {
        maxFitnessLabel.setText("Max Fitness: "+Math.round(fitness));
    }
        
    public void setPopAliveValue(int alive) {
        popAliveLabel.setText("Population alive: "+alive);
    }
    
    public void setVisibleStatus(boolean visible) {
        statusPanel.setVisible(visible);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewGroup = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        createBarrierButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        nextgenButton = new javax.swing.JButton();
        pauseLearningButton = new javax.swing.JButton();
        resumeLearningButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        generationCountLabel = new javax.swing.JLabel();
        popAliveLabel = new javax.swing.JLabel();
        maxFitnessLabel = new javax.swing.JLabel();
        playgroundPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        loadItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        savePopulationItem = new javax.swing.JMenuItem();
        loadPopulationItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        networkItem = new javax.swing.JMenuItem();
        populationItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        resetViewItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        viewModMenu = new javax.swing.JMenu();
        viewModFreeRadio = new javax.swing.JRadioButtonMenuItem();
        viewModLockRadio = new javax.swing.JRadioButtonMenuItem();
        editMenu = new javax.swing.JMenu();
        newBarrierItem = new javax.swing.JMenuItem();
        changeBarrierItem = new javax.swing.JMenuItem();
        deleteBarrierItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NeuralSandbox");
        setName("NeuralSandbox"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        createBarrierButton.setText("Add Barrier");
        createBarrierButton.setToolTipText("Create new barrier");
        createBarrierButton.setFocusable(false);
        createBarrierButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createBarrierButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createBarrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBarrierButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(createBarrierButton);

        changeButton.setText("Change barrier");
        changeButton.setToolTipText("Click and hold to any barrier to change it's position.");
        changeButton.setFocusable(false);
        changeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(changeButton);

        deleteButton.setText("Delete barrier");
        deleteButton.setToolTipText("Click to any barrier to delete it");
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(deleteButton);

        startButton.setText("New population");
        startButton.setToolTipText("Starts evolving neural network according to the settings");
        startButton.setFocusable(false);
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(startButton);

        nextgenButton.setText("Skipgen");
        nextgenButton.setToolTipText("Skips current generation");
        nextgenButton.setFocusable(false);
        nextgenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextgenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextgenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextgenButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(nextgenButton);

        pauseLearningButton.setText("Pause learning");
        pauseLearningButton.setFocusable(false);
        pauseLearningButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pauseLearningButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pauseLearningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseLearningButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pauseLearningButton);

        resumeLearningButton.setText("Resume learning");
        resumeLearningButton.setFocusable(false);
        resumeLearningButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resumeLearningButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resumeLearningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeLearningButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(resumeLearningButton);

        statusPanel.setPreferredSize(new java.awt.Dimension(1140, 50));
        statusPanel.setLayout(new java.awt.GridLayout(1, 0));

        generationCountLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        generationCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generationCountLabel.setText("Generation");
        generationCountLabel.setPreferredSize(new java.awt.Dimension(63, 50));
        statusPanel.add(generationCountLabel);

        popAliveLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        popAliveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        popAliveLabel.setText("Pop Alive");
        statusPanel.add(popAliveLabel);

        maxFitnessLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        maxFitnessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxFitnessLabel.setText("Max Fitness");
        statusPanel.add(maxFitnessLabel);

        playgroundPanel.setPreferredSize(new Dimension(pg.getScaledValue(1200), pg.getScaledValue(800))
        );

        javax.swing.GroupLayout playgroundPanelLayout = new javax.swing.GroupLayout(playgroundPanel);
        playgroundPanel.setLayout(playgroundPanelLayout);
        playgroundPanelLayout.setHorizontalGroup(
            playgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        playgroundPanelLayout.setVerticalGroup(
            playgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        saveItem.setText("Save level...");
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveItem);

        loadItem.setText("Load level...");
        loadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadItem);
        fileMenu.add(jSeparator2);

        savePopulationItem.setText("Save population...");
        savePopulationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePopulationItemActionPerformed(evt);
            }
        });
        fileMenu.add(savePopulationItem);

        loadPopulationItem.setText("Load population...");
        loadPopulationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPopulationItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadPopulationItem);

        jMenuBar1.add(fileMenu);

        settingsMenu.setText("Settings");

        networkItem.setText("Neural network");
        networkItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkItemActionPerformed(evt);
            }
        });
        settingsMenu.add(networkItem);

        populationItem.setText("Population");
        populationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populationItemActionPerformed(evt);
            }
        });
        settingsMenu.add(populationItem);

        jMenuBar1.add(settingsMenu);

        viewMenu.setText("View");

        resetViewItem.setText("Center playground");
        resetViewItem.setToolTipText("Moves camera to left up corner of playground");
        resetViewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetViewItemActionPerformed(evt);
            }
        });
        viewMenu.add(resetViewItem);
        viewMenu.add(jSeparator1);

        viewModMenu.setText("View mod");

        viewGroup.add(viewModFreeRadio);
        viewModFreeRadio.setSelected(true);
        viewModFreeRadio.setText("Free look");
        viewModFreeRadio.setToolTipText("Free look around playground use 'ALT' and drag");
        viewModFreeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewModFreeRadioActionPerformed(evt);
            }
        });
        viewModMenu.add(viewModFreeRadio);

        viewGroup.add(viewModLockRadio);
        viewModLockRadio.setText("Follow the best");
        viewModLockRadio.setToolTipText("Follows the fittest individual");
        viewModLockRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewModLockRadioActionPerformed(evt);
            }
        });
        viewModMenu.add(viewModLockRadio);

        viewMenu.add(viewModMenu);

        jMenuBar1.add(viewMenu);

        editMenu.setText("Edit");

        newBarrierItem.setText("New barrier");
        newBarrierItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBarrierItemActionPerformed(evt);
            }
        });
        editMenu.add(newBarrierItem);

        changeBarrierItem.setText("Change barrier");
        changeBarrierItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBarrierItemActionPerformed(evt);
            }
        });
        editMenu.add(changeBarrierItem);

        deleteBarrierItem.setText("Delete barrier");
        deleteBarrierItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBarrierItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteBarrierItem);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(playgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBarrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBarrierButtonActionPerformed
        pg.createBarrier();
    }//GEN-LAST:event_createBarrierButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        pg.deleteBarrier();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        saveLevel();
    }//GEN-LAST:event_saveItemActionPerformed

    private void loadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadItemActionPerformed
        loadLevel();
    }//GEN-LAST:event_loadItemActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        pg.startEvolution(null);
    }//GEN-LAST:event_startButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        pg.changeBarrier();
    }//GEN-LAST:event_changeButtonActionPerformed

    private void nextgenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextgenButtonActionPerformed
        pg.nextgen();
    }//GEN-LAST:event_nextgenButtonActionPerformed

    private void networkItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkItemActionPerformed
        NeuralNetworkSetting nns = new NeuralNetworkSetting(this, true, pg);
        nns.setVisible(true);
        pg.setBrainTemplate(nns.getNeuronModel());
        pg.setCarFeedbackSensor(nns.isFeedback());
    }//GEN-LAST:event_networkItemActionPerformed

    private void populationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populationItemActionPerformed
        PopulationSetting ps = new PopulationSetting(this, true, pg);
        ps.setVisible(true);
        if(!(ps.getMutationRate() == -1 || ps.getPopCount() == -1)) {
            pg.setMutationRate(ps.getMutationRate());
            pg.setPopCount(ps.getPopCount());
            pg.setPopulationTimerDelay(ps.getTimerDelay());
        }
    }//GEN-LAST:event_populationItemActionPerformed

    private void savePopulationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePopulationItemActionPerformed
        savePopulation();
    }//GEN-LAST:event_savePopulationItemActionPerformed

    private void loadPopulationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPopulationItemActionPerformed
        loadPopulation();
    }//GEN-LAST:event_loadPopulationItemActionPerformed

    private void resetViewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetViewItemActionPerformed
        pg.setLocation(0,0);
    }//GEN-LAST:event_resetViewItemActionPerformed

    private void newBarrierItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBarrierItemActionPerformed
        pg.createBarrier();
    }//GEN-LAST:event_newBarrierItemActionPerformed

    private void changeBarrierItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBarrierItemActionPerformed
        pg.changeBarrier();
    }//GEN-LAST:event_changeBarrierItemActionPerformed

    private void deleteBarrierItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBarrierItemActionPerformed
        pg.deleteBarrier();
    }//GEN-LAST:event_deleteBarrierItemActionPerformed

    private void viewModFreeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewModFreeRadioActionPerformed
        pg.setViewMod(0);
    }//GEN-LAST:event_viewModFreeRadioActionPerformed

    private void viewModLockRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewModLockRadioActionPerformed
        pg.setViewMod(1);
    }//GEN-LAST:event_viewModLockRadioActionPerformed

    private void pauseLearningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseLearningButtonActionPerformed
        pg.setLearning(false);
        pauseLearningButton.setVisible(false);
        resumeLearningButton.setVisible(true);
    }//GEN-LAST:event_pauseLearningButtonActionPerformed

    private void resumeLearningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeLearningButtonActionPerformed
        pg.setLearning(true);
        resumeLearningButton.setVisible(false);
        pauseLearningButton.setVisible(true);
    }//GEN-LAST:event_resumeLearningButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    static String readFile(String path, Charset encoding) throws IOException {
        byte[] encoded = Files.readAllBytes(Paths.get(path));
        return new String(encoded, encoding);
    }
    
    public boolean savePopulation() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogType(1);
        fc.setCurrentDirectory(new File("."));
        
        String path;
        
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getPath();
        }
        else {
            return false;
        }
        
        XStream xstream = new XStream(new DomDriver()); 
        String xml = xstream.toXML(pg.getPopulation().getGeneration());
        xml += '\n';
        xml += xstream.toXML(pg.getPopulation().getAllBrains());
        
        try (PrintWriter out = new PrintWriter(path)) {
            out.println(xml);
            return true;
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Can't save population!\n"+e, "Error",
            JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    public boolean loadPopulation() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogType(1);
        fc.setCurrentDirectory(new File("."));
        
        String path;
        
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getPath();
        }
        else {
            return false;
        }
        
        XStream xstream = new XStream(new DomDriver()); 
        try {
            String xml = readFile(path, Charset.defaultCharset());
            
            String x1 = xml.substring(0, xml.indexOf("<list>"));
            String x2 = xml.substring(xml.indexOf("<list>"));
            
            int generation = (Integer)xstream.fromXML(x1);
            ArrayList<ArrayList<ArrayList<ArrayList<Double>>>> allBrains = (ArrayList<ArrayList<ArrayList<ArrayList<Double>>>>)xstream.fromXML(x2);
            
            ArrayList<CarAI> individuals = new ArrayList(allBrains.size());
            
            for(int i = 0; i < allBrains.size(); i++) {
                individuals.add(new CarAI(this.pg, pg.getSpawn().getSpawnpoint(), allBrains.get(i), pg.isCarFeedbackSensor()));
            }
            
            Population pop = new Population(this.pg, individuals, generation, pg.getMutationRate(), pg.getPopulationTimerDelay());
            pg.setPopulation(pop);
            
            return true;
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Can't load population!\n"+e, "Error",
            JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    public boolean saveLevel() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogType(1);
        fc.setCurrentDirectory(new File("."));
        
        String path;
        
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getPath();
        }
        else {
            return false;
        }
        
        XStream xstream = new XStream(new DomDriver()); 
        ArrayList<BarrierSkeleton> skelBars = new ArrayList();
        for(Barrier b : pg.getBarriers()) {
            skelBars.add(b.getSkeleton());
        }
        String xml = xstream.toXML(skelBars);
        xml += '\n';
        xstream.alias("Spawnpoint", Point.class);
        xml += xstream.toXML(pg.getSpawn().getPos());
        xml += '\n';
        xstream.alias("Finishpoint", Point.class);
        xml += xstream.toXML(pg.getFinish().getPos());
        
        try (PrintWriter out = new PrintWriter(path)) {
            out.println(xml);
            return true;
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Can't save level!\n"+e, "Error",
            JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    public boolean loadLevel() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogType(1);
        fc.setCurrentDirectory(new File("."));
        
        String path;
        
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getPath();
        }
        else {
            return false;
        }
        
        XStream xstream = new XStream(new DomDriver()); 
        try {
            String xml = readFile(path, Charset.defaultCharset());
            
            //Barriery
            String firstpoint = (xml.indexOf("<Spawn") < xml.indexOf("<Finish") ? "<Spawn" : "<Finish");
            String barriersXML = xml.substring(0, xml.indexOf(firstpoint));
            
            //Spawn
            String spawnPointXML = xml.substring(xml.indexOf("<Spawnpoint>"),xml.indexOf("</Spawnpoint>")+("</Spawnpoint>".length()));
            
            //Finish
            String finishPointXML = xml.substring(xml.indexOf("<Finishpoint>"),xml.indexOf("</Finishpoint>")+("</Finishpoint>".length()));
            
            ArrayList<BarrierSkeleton> skelBars = (ArrayList<BarrierSkeleton>)xstream.fromXML(barriersXML);
            xstream.alias("Spawnpoint", Point.class);
            Point spawnPoint = (Point)xstream.fromXML(spawnPointXML);
            xstream.alias("Finishpoint", Point.class);
            Point finishPoint = (Point)xstream.fromXML(finishPointXML);
            
            pg.getSpawn().setPos(spawnPoint);
            pg.getFinish().setPos(finishPoint);
            
            ArrayList<Barrier> bars = new ArrayList();
            for(BarrierSkeleton bs : skelBars) {
                bars.add(new Barrier(bs.getLenght(), bs.getWidth(), pg, bs.getS(), bs.getAngle()));
            }
            
            pg.setBarriers(bars);
            return true;
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Can't load level!\n"+e, "Error",
            JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changeBarrierItem;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton createBarrierButton;
    private javax.swing.JMenuItem deleteBarrierItem;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel generationCountLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem loadItem;
    private javax.swing.JMenuItem loadPopulationItem;
    private javax.swing.JLabel maxFitnessLabel;
    private javax.swing.JMenuItem networkItem;
    private javax.swing.JMenuItem newBarrierItem;
    private javax.swing.JButton nextgenButton;
    private javax.swing.JButton pauseLearningButton;
    private javax.swing.JPanel playgroundPanel;
    private javax.swing.JLabel popAliveLabel;
    private javax.swing.JMenuItem populationItem;
    private javax.swing.JMenuItem resetViewItem;
    private javax.swing.JButton resumeLearningButton;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JMenuItem savePopulationItem;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel statusPanel;
    private javax.swing.ButtonGroup viewGroup;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JRadioButtonMenuItem viewModFreeRadio;
    private javax.swing.JRadioButtonMenuItem viewModLockRadio;
    private javax.swing.JMenu viewModMenu;
    // End of variables declaration//GEN-END:variables
}
